Handle edge case where socket is None
* The following exception happens randomly on startup:

```
Exception has occurred: AttributeError
'NoneType' object has no attribute 'recv'
File "paho/mqtt/client.py", line 640, in _sock_recv
```

* The root cause is unknown, but this allows the library to reconnect
  gracefully.

Signed-off-by: Robert DeRose <RobertDeRose@gmail.com>